⚠️ Reply with number(s) to delete (space separated)

1. [File📄] 0admin.js
2. [File📄] 4k.js
3. [File📄] Admin.js
4. [File📄] Autoreply.js
5. [File📄] Help.js
6. [File📄] Helpall.js
7. [File📄] Info.js
8. [File📄] Mentionadmin.js
9. [File📄] Owner.js
10. [File📄] Prefix.js
11. [File📄] acp.js
12. [File📄] adbot.js
13. [File📄] adduser.js
14. [File📄] adminonly.js
15. [File📄] age.js
16. [File📄] ai.js
17. [File📄] album.js
18. [File📄] allbox.js
19. [File📄] ang-bn.js
20. [File📄] ang-en.js
21. [File📄] anime.js
22. [File📄] antijoin.js
23. [File📄] antiout.js
24. [File📄] arrest.js
25. [File📄] art.js
26. [File📄] autodl.js
27. [File📄] autoreact.js
28. [File📄] autoseen.js
29. [File📄] autotime.js
30. [File📄] baby.js
31. [File📄] balance.js
32. [File📄] ban.js
33. [File📄] bday.js
34. [File📄] bestFriend.js
35. [File📄] bf.js
36. [File📄] birthday.js
37. [File📄] box.js
38. [File📄] boxadmin.js
39. [File📄] boxinfo.js
40. [File📄] boypp.js
41. [File📄] bro.js
42. [File📄] broken.js
43. [File📄] btsRost.js
44. [Folder🗂️] cache
45. [File📄] caption.js
46. [File📄] catbox.js
47. [File📄] chor.js
48. [File📄] cmdinstall.js
49. [File📄] cmdstore.js
50. [File📄] config.js
51. [File📄] console.js
52. [Folder🗂️] count-by-thread
53. [File📄] couple.js
54. [File📄] cpt.js
55. [File📄] crush.js
56. [File📄] daily.js
57. [File📄] dog.js
58. [File📄] emojiVoice.js
59. [File📄] emojimix.js
60. [File📄] fbcover.js
61. [File📄] fblink.js
62. [File📄] file.js
63. [File📄] flux.js
64. [File📄] font.js
65. [File📄] fork.js
66. [File📄] fp.js
67. [File📄] friends.js
68. [File📄] getlink.js
69. [File📄] gf.js
70. [File📄] girlpp.js
71. [File📄] give.js
72. [File📄] google.js
73. [File📄] groupemoji.js
74. [File📄] groupimage.js
75. [File📄] groupname.js
76. [File📄] hack.js
77. [File📄] hug.js
78. [File📄] hug2.js
79. [File📄] imgur.js
80. [File📄] inbox.js
81. [File📄] islamic.js
82. [File📄] join.js
83. [File📄] kick.js
84. [File📄] kickall.js
85. [File📄] kiss.js
86. [File📄] listadmin.js
87. [File📄] listbox.js
88. [File📄] listfriend.js
89. [File📄] load.js
90. [File📄] love.js
91. [File📄] married.js
92. [File📄] married2.js
93. [File📄] megi_chudi.js
94. [File📄] mention.js
95. [File📄] mp3.js
96. [File📄] murgi.js
97. [File📄] needgf.js
98. [File📄] newbox.js
99. [File📄] night.js
100. [Folder🗂️] noprefix
101. [File📄] noti2.js
102. [File📄] notice.js
103. [File📄] numinfo.js
104. [File📄] out.js
105. [File📄] outall.js
106. [File📄] pair.js
107. [File📄] pairing.js
108. [File📄] pending.js
109. [File📄] pick.js
110. [File📄] poli.js
111. [File📄] post.js
112. [File📄] pp.js
113. [File📄] profile.js
114. [File📄] prompt.js
115. [File📄] quiz.js
116. [File📄] random.js
117. [File📄] rankup.js
118. [File📄] rasian.js
119. [File📄] reaction-px.js
120. [File📄] removebg.js
121. [File📄] resend.js
122. [File📄] restrat.js
123. [File📄] rip.js
124. [File📄] rules.js
125. [File📄] say.js
126. [File📄] search.js
127. [File📄] selfadmin.js
128. [File📄] setbot.js
129. [File📄] setemoji.js
130. [File📄] setexp.js
131. [File📄] setname.js
132. [File📄] setprefix.js
133. [File📄] settings.js
134. [File📄] shortcut.js
135. [File📄] sing.js
136. [File📄] slap.js
137. [File📄] slot.js
138. [File📄] song.js
139. [File📄] spam.js
140. [File📄] ss.js
141. [File📄] stalk.js
142. [File📄] sura.js
143. [File📄] tag.js
144. [File📄] text.js
145. [File📄] thread.js
146. [File📄] tid.js
147. [File📄] toilet.js
148. [File📄] top.js
149. [File📄] uid.js
150. [File📄] unsend.js
151. [File📄] upt.js
152. [File📄] uptime.js
153. [File📄] video.js
154. [Folder🗂️] wall
155. [File📄] wallpaper.js
156. [File📄] war.js
157. [File📄] weather.js
158. [File📄] wife.js
159. [File📄] wish.js
160. [File📄] x.js
161. [File📄] youtube.js
